version: 2.1

jobs:
  ubuntu1804:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: add-apt-repository ppa:snaipewastaken/ppa
      - run: apt update && apt -y install gcc clang cmake criterion-dev
      - run: chmod +x .ci/run_tests.sh

  debianLatestStable:
    docker:
      - image: debian:latest
    steps:
      - checkout
      - run: add-apt-repository ppa:snaipewastaken/ppa
      - run: apt update && apt -y install git gcc clang cmake criterion-dev
      - run: chmod +x .ci/run_tests.sh

workflows:
  version: 2
  build:
    jobs:
      - ubuntu1804
      - debianLatestStable
