version: 2.0

jobs:
  debianLatestStable:
    docker:
      - image: debian:latest
    steps:
      - checkout
      - run: apt update && apt -y install git gcc clang cmake libcriterion-dev 
      - run: chmod +x .circleci/build_and_tests.sh

  fedoraLatestStable:
    docker:
      - image: fedora:latest
    steps:
      - checkout
      - run: dnf -y update && dnf -y install git gcc cmake make libgcrypt-devel 
      - run: chmod +x .circleci/build_only.sh

  archlinux:
    docker:
      - image: archlinux:latest
    steps:
      - checkout
      - run: pacman -Syu --noconfirm && pacman -S --noconfirm pkg-config git gcc cmake make
      - run: chmod +x .circleci/build_only.sh

workflows:
  version: 2
  build:
    jobs:
      - debianLatestStable
      - fedoraLatestStable
      - archlinux

